name: build-output-directory

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
             
      - name: npm install for React frontend
        run: |
          cd BetterFront-start/BetterFront-React
          npm install
          
      - name: npm build output directory
        run: |
          cd BetterFront-start/BetterFront-React
          npm run build
          
      - name: Verify output directory
        run: |
          DIR="BetterFront-start/BetterFront-NodeJS/frontend"
          if [ ! -d "$DIR" ]; then
            echo "❌ Directory $DIR does not exist!"
            exit 1
          fi
          if [ -z "$(ls -A $DIR)" ]; then
            echo "❌ Directory $DIR is empty!"
            exit 1
          fi
          echo "✅ Directory $DIR exists and is not empty."

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: BetterFront-start/BetterFront-NodeJS/frontend
          
  nodejs-npm-intall:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: BetterFront-start/BetterFront-NodeJS/frontend
    
      - name: npm install for NodeJS backend
        run: |
          cd BetterFront-start/BetterFront-NodeJS
          npm install

      - name: Upload NodeJS with frontend
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-web-server
          path: BetterFront-start/BetterFront-NodeJS/    

      
